// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Triggr.Data;

namespace Triggr.UI.Migrations
{
    [DbContext(typeof(TriggrContext))]
    [Migration("20180305152716_webhook_info")]
    partial class webhook_info
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("Triggr.Data.Repository", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("OwnerName");

                    b.Property<string>("Provider");

                    b.Property<string>("Reference");

                    b.Property<string>("Token");

                    b.Property<DateTimeOffset>("UpdatedTime");

                    b.Property<string>("Url");

                    b.Property<bool>("WebHook");

                    b.Property<string>("WebHookId");

                    b.HasKey("Id");

                    b.ToTable("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
